version: '3.0'

services:
  influxdb:
    image: influxdb:2.7.4
    container_name: influxdb-rdz
    ports:
      - "18086:8086"
    env_file: configurations.env
    volumes:
      - ./data_container/influxdata:/var/lib/influxdb2
      - ./data_container/config:/etc/influxdb2
    restart: always

  telegraf:
    image: telegraf:1.21
    container_name: telegraf-rdz
    depends_on:
      - influxdb
    hostname: "serverpe"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.1
    container_name: grafana-rdz
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    links:
      - influxdb
    depends_on:
      - influxdb
    restart: on-failure:3

    python-query:
      build: ./influx-exporter
      container_name: python-query-rdz
      env_file: ./influx-exporter/.env
      volumes:
      - ./influx-exporter:/app
      depends_on:
      - influxdb
      restart: unless-stopped

networks:
  default:
    name: iot-internal-network
    external: true
    driver: bridge